import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateProcessDrafts1740000000004 implements MigrationInterface {
  name = 'CreateProcessDrafts1740000000004';

  async up(queryRunner: QueryRunner): Promise<void> {
    const schema = requiredIdentifier('ORACLE_SCHEMA');
    const runtimeUser = requiredIdentifier('DATABASE_USER');
    if (runtimeUser === schema) {
      throw new Error('DATABASE_USER must be separate from ORACLE_SCHEMA for process grants');
    }
    const table = (name: string) => `"${schema}"."${name}"`;

    await queryRunner.query(`CREATE SEQUENCE ${table('PROCESS_CODE_SEQ')} START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE`);
    await queryRunner.query(`CREATE TABLE ${table('PROCESS')} (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      CODE VARCHAR2(32 CHAR) NOT NULL UNIQUE,
      OWNER_USER_ID NUMBER NOT NULL REFERENCES ${table('APP_USER')}(ID),
      CURRENT_VERSION_ID NUMBER,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1))
    )`);
    await queryRunner.query(`CREATE TABLE ${table('PROCESS_VERSION')} (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      PROCESS_ID NUMBER NOT NULL REFERENCES ${table('PROCESS')}(ID),
      VERSION_NUMBER NUMBER(6) NOT NULL,
      STATUS VARCHAR2(20 CHAR) NOT NULL CHECK (STATUS = 'Borrador'),
      MACROPROCESS_ID NUMBER NOT NULL REFERENCES ${table('MACROPROCESS')}(ID),
      PROCESS_TYPE_ID NUMBER NOT NULL REFERENCES ${table('PROCESS_TYPE')}(ID),
      PARENT_PROCESS_ID NUMBER REFERENCES ${table('PROCESS')}(ID),
      NAME VARCHAR2(250 CHAR),
      ALIAS VARCHAR2(250 CHAR),
      DESCRIPTION CLOB,
      OBJECTIVE CLOB,
      SCOPE CLOB,
      INPUTS CLOB,
      OUTPUTS CLOB,
      SUPPLIERS CLOB,
      CLIENTS CLOB,
      INVOLVED_PARTIES CLOB,
      STARTS_WHEN CLOB,
      ENDS_WHEN CLOB,
      DEVELOPMENT_PLAN CLOB,
      OPERATION CLOB,
      DESIGN CLOB,
      VALIDATION CLOB,
      BUSINESS_AREA VARCHAR2(250 CHAR),
      SUBPROCESS_TYPE VARCHAR2(250 CHAR),
      CRITICALITY VARCHAR2(250 CHAR),
      AUTOMATION_LEVEL VARCHAR2(250 CHAR),
      PERIODICITY VARCHAR2(250 CHAR),
      REVISION NUMBER(10) DEFAULT 1 NOT NULL,
      CONSTRAINT UQ_PROCESS_VERSION_NUMBER UNIQUE (PROCESS_ID, VERSION_NUMBER)
    )`);
    await queryRunner.query(`ALTER TABLE ${table('PROCESS')}
      ADD CONSTRAINT FK_PROCESS_CURRENT_VERSION FOREIGN KEY (CURRENT_VERSION_ID)
      REFERENCES ${table('PROCESS_VERSION')}(ID)`);
    await queryRunner.query(`CREATE INDEX ${table('IX_PROCESS_OWNER')} ON ${table('PROCESS')}(OWNER_USER_ID)`);
    await queryRunner.query(`CREATE INDEX ${table('IX_VERSION_PROCESS')} ON ${table('PROCESS_VERSION')}(PROCESS_ID)`);
    await queryRunner.query(`CREATE INDEX ${table('IX_VERSION_MACRO')} ON ${table('PROCESS_VERSION')}(MACROPROCESS_ID)`);
    await queryRunner.query(`CREATE INDEX ${table('IX_VERSION_TYPE')} ON ${table('PROCESS_VERSION')}(PROCESS_TYPE_ID)`);
    await queryRunner.query(`CREATE INDEX ${table('IX_VERSION_PARENT')} ON ${table('PROCESS_VERSION')}(PARENT_PROCESS_ID)`);
    await queryRunner.query(`GRANT SELECT, INSERT, UPDATE ON ${table('PROCESS')} TO "${runtimeUser}"`);
    await queryRunner.query(`GRANT SELECT, INSERT, UPDATE ON ${table('PROCESS_VERSION')} TO "${runtimeUser}"`);
    await queryRunner.query(`GRANT SELECT ON ${table('PROCESS_CODE_SEQ')} TO "${runtimeUser}"`);
  }

  async down(): Promise<void> {
    throw new Error('Process drafts contain business records and cannot be removed by migration rollback.');
  }
}

function requiredIdentifier(name: 'ORACLE_SCHEMA' | 'DATABASE_USER'): string {
  const value = process.env[name]?.trim().toUpperCase();
  if (!value || !/^[A-Z][A-Z0-9_$#]{0,29}$/.test(value)) {
    throw new Error(`${name} must be a valid Oracle identifier`);
  }
  return value;
}
