import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateMissingAuditTable1740000000003 implements MigrationInterface {
  name = 'CreateMissingAuditTable1740000000003';

  async up(queryRunner: QueryRunner): Promise<void> {
    const schema = requiredIdentifier('ORACLE_SCHEMA');
    const runtimeUser = requiredIdentifier('DATABASE_USER');
    if (runtimeUser === schema) {
      throw new Error('DATABASE_USER must be separate from ORACLE_SCHEMA for audit grants');
    }
    const table = `"${schema}"."AUDIT"`;
    const existing = await queryRunner.query(
      `SELECT COUNT(*) AS "count" FROM ALL_TABLES WHERE OWNER = :1 AND TABLE_NAME = 'AUDIT'`,
      [schema]
    );

    if (Number(existing[0].count ?? existing[0].COUNT) === 0) {
      await queryRunner.query(`CREATE TABLE ${table} (
        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'UTC') NOT NULL,
        ACTOR_USER_ID NUMBER REFERENCES "${schema}"."APP_USER"(ID),
        ACTION VARCHAR2(80 CHAR) NOT NULL,
        ENTITY_TYPE VARCHAR2(40 CHAR) NOT NULL,
        ENTITY_ID VARCHAR2(80 CHAR) NOT NULL,
        BEFORE_VALUE CLOB,
        AFTER_VALUE CLOB
      )`);
    }

    const index = await queryRunner.query(
      `SELECT COUNT(*) AS "count" FROM ALL_INDEXES WHERE OWNER = :1 AND INDEX_NAME = 'IX_AUDIT_CREATED'`,
      [schema]
    );
    if (Number(index[0].count ?? index[0].COUNT) === 0) {
      await queryRunner.query(`CREATE INDEX "${schema}"."IX_AUDIT_CREATED" ON ${table}(CREATED_AT)`);
    }

    await queryRunner.query(`GRANT SELECT, INSERT ON ${table} TO "${runtimeUser}"`);
  }

  async down(): Promise<void> {
    throw new Error('Audit table repair is intentionally irreversible to preserve audit history.');
  }
}

function requiredIdentifier(name: 'ORACLE_SCHEMA' | 'DATABASE_USER'): string {
  const value = process.env[name]?.trim().toUpperCase();
  if (!value || !/^[A-Z][A-Z0-9_$#]{0,29}$/.test(value)) {
    throw new Error(`${name} must be a valid Oracle identifier`);
  }
  return value;
}
