import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateProcessRisks1740000000005 implements MigrationInterface {
  name = 'CreateProcessRisks1740000000005';

  async up(queryRunner: QueryRunner): Promise<void> {
    const schema = requiredIdentifier('ORACLE_SCHEMA');
    const runtimeUser = requiredIdentifier('DATABASE_USER');
    if (runtimeUser === schema) {
      throw new Error('DATABASE_USER must be separate from ORACLE_SCHEMA for risk grants');
    }
    const table = (name: string) => `"${schema}"."${name}"`;

    await queryRunner.query(`CREATE TABLE ${table('RISK_TYPE')} (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      NAME VARCHAR2(120 CHAR) NOT NULL UNIQUE,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1))
    )`);
    await queryRunner.query(`CREATE TABLE ${table('RISK_LEVEL')} (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      NAME VARCHAR2(120 CHAR) NOT NULL UNIQUE,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1))
    )`);
    await queryRunner.query(`CREATE TABLE ${table('PROCESS_RISK')} (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      PROCESS_ID NUMBER NOT NULL REFERENCES ${table('PROCESS')}(ID),
      DESCRIPTION CLOB NOT NULL,
      CAUSE CLOB NOT NULL,
      CONSEQUENCE CLOB NOT NULL,
      RISK_TYPE_ID NUMBER NOT NULL REFERENCES ${table('RISK_TYPE')}(ID),
      RISK_LEVEL_ID NUMBER NOT NULL REFERENCES ${table('RISK_LEVEL')}(ID),
      CREATED_BY_USER_ID NUMBER NOT NULL REFERENCES ${table('APP_USER')}(ID),
      CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'UTC') NOT NULL
    )`);
    await queryRunner.query(`CREATE INDEX ${table('IX_PRISK_PROCESS')} ON ${table('PROCESS_RISK')}(PROCESS_ID, ID)`);
    await queryRunner.query(`CREATE INDEX ${table('IX_PRISK_TYPE')} ON ${table('PROCESS_RISK')}(RISK_TYPE_ID)`);
    await queryRunner.query(`CREATE INDEX ${table('IX_PRISK_LEVEL')} ON ${table('PROCESS_RISK')}(RISK_LEVEL_ID)`);

    await queryRunner.query(`GRANT SELECT, INSERT ON ${table('PROCESS_RISK')} TO "${runtimeUser}"`);
    await queryRunner.query(`GRANT SELECT, INSERT, UPDATE ON ${table('RISK_TYPE')} TO "${runtimeUser}"`);
    await queryRunner.query(`GRANT SELECT, INSERT, UPDATE ON ${table('RISK_LEVEL')} TO "${runtimeUser}"`);
  }

  async down(): Promise<void> {
    throw new Error('Process risks and reference lists contain business data and cannot be removed by migration rollback.');
  }
}

function requiredIdentifier(name: 'ORACLE_SCHEMA' | 'DATABASE_USER'): string {
  const value = process.env[name]?.trim().toUpperCase();
  if (!value || !/^[A-Z][A-Z0-9_$#]{0,29}$/.test(value)) {
    throw new Error(`${name} must be a valid Oracle identifier`);
  }
  return value;
}
