import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialIncrementOne1740000000000 implements MigrationInterface {
  name = 'InitialIncrementOne1740000000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    const schema = process.env.ORACLE_SCHEMA?.trim().toUpperCase();
    if (!schema || !/^[A-Z][A-Z0-9_$#]{0,29}$/.test(schema)) {
      throw new Error('ORACLE_SCHEMA must be a valid Oracle schema name');
    }
    const table = (name: string) => `"${schema}"."${name}"`;
    const sequence = (name: string) => `"${schema}"."${name}"`;

    await queryRunner.query(`CREATE TABLE ${table('APP_USER')} (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      IS_DEMO NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_DEMO IN (0, 1)),
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1))
    )`);
    await queryRunner.query(`CREATE TABLE ${table('USER_IDENTITY')} (
      USER_ID NUMBER PRIMARY KEY REFERENCES ${table('APP_USER')}(ID),
      DISPLAY_NAME VARCHAR2(120 CHAR) NOT NULL,
      EMAIL VARCHAR2(254 CHAR) NOT NULL UNIQUE,
      PROVIDER VARCHAR2(20 CHAR) NOT NULL CHECK (PROVIDER IN ('DEMO', 'GOOGLE'))
    )`);
    await queryRunner.query(`CREATE TABLE ${table('APP_PROFILE')} (
      CODE VARCHAR2(30 CHAR) PRIMARY KEY,
      NAME VARCHAR2(80 CHAR) NOT NULL
    )`);
    await queryRunner.query(`CREATE TABLE ${table('USER_PROFILE')} (
      USER_ID NUMBER NOT NULL REFERENCES ${table('APP_USER')}(ID),
      PROFILE_CODE VARCHAR2(30 CHAR) NOT NULL REFERENCES ${table('APP_PROFILE')}(CODE),
      CONSTRAINT PK_USER_PROFILE PRIMARY KEY (USER_ID, PROFILE_CODE)
    )`);
    await queryRunner.query(`CREATE TABLE ${table('DEMO_IDENTITY')} (
      USER_ID NUMBER PRIMARY KEY REFERENCES ${table('APP_USER')}(ID)
    )`);
    await queryRunner.query(`CREATE TABLE ${table('ADMIN_CONTROL')} (
      ID NUMBER PRIMARY KEY CHECK (ID = 1)
    )`);
    await queryRunner.query(`INSERT INTO ${table('ADMIN_CONTROL')} (ID) VALUES (1)`);
    await queryRunner.query(`CREATE TABLE ${table('MACROPROCESS')} (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      CODE VARCHAR2(32 CHAR) NOT NULL UNIQUE,
      NAME VARCHAR2(120 CHAR) NOT NULL,
      DESCRIPTION VARCHAR2(1000 CHAR),
      SORT_ORDER NUMBER(6) NOT NULL,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1))
    )`);
    await queryRunner.query(`CREATE SEQUENCE ${sequence('MACROPROCESS_CODE_SEQ')} START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE`);
    await queryRunner.query(`CREATE TABLE ${table('PROCESS_TYPE')} (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      NAME VARCHAR2(120 CHAR) NOT NULL UNIQUE,
      IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1))
    )`);
    await queryRunner.query(`CREATE TABLE ${table('APP_SESSION')} (
      SESSION_HASH CHAR(64 CHAR) PRIMARY KEY,
      USER_ID NUMBER NOT NULL REFERENCES ${table('APP_USER')}(ID),
      CSRF_HASH CHAR(64 CHAR) NOT NULL,
      LAST_ACTIVITY TIMESTAMP WITH TIME ZONE NOT NULL,
      EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL
    )`);
    await queryRunner.query(`CREATE INDEX "${schema}"."IX_APP_SESSION_EXPIRY" ON ${table('APP_SESSION')}(EXPIRES_AT)`);
    await queryRunner.query(`CREATE TABLE ${table('AUDIT')} (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'UTC') NOT NULL,
      ACTOR_USER_ID NUMBER REFERENCES ${table('APP_USER')}(ID),
      ACTION VARCHAR2(80 CHAR) NOT NULL,
      ENTITY_TYPE VARCHAR2(40 CHAR) NOT NULL,
      ENTITY_ID VARCHAR2(80 CHAR) NOT NULL,
      BEFORE_VALUE CLOB,
      AFTER_VALUE CLOB
    )`);
    await queryRunner.query(`CREATE INDEX "${schema}"."IX_AUDIT_CREATED" ON ${table('AUDIT')}(CREATED_AT)`);
    await queryRunner.query(`CREATE TABLE ${table('SECURITY_EVENT')} (
      ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT (SYSTIMESTAMP AT TIME ZONE 'UTC') NOT NULL,
      ACTOR_USER_ID NUMBER REFERENCES ${table('APP_USER')}(ID),
      IP_ADDRESS VARCHAR2(64 CHAR) NOT NULL,
      EVENT VARCHAR2(40 CHAR) NOT NULL,
      RESULT VARCHAR2(20 CHAR) NOT NULL CHECK (RESULT IN ('SUCCESS', 'REJECTED'))
    )`);
    await queryRunner.query(`CREATE TABLE ${table('SECURITY_EVENT_IP')} (
      SECURITY_EVENT_ID NUMBER PRIMARY KEY REFERENCES ${table('SECURITY_EVENT')}(ID),
      IP_ADDRESS VARCHAR2(64 CHAR) NOT NULL
    )`);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    const schema = process.env.ORACLE_SCHEMA?.trim().toUpperCase();
    if (!schema || !/^[A-Z][A-Z0-9_$#]{0,29}$/.test(schema)) {
      throw new Error('ORACLE_SCHEMA must be a valid Oracle schema name');
    }
    const table = (name: string) => `"${schema}"."${name}"`;
    for (const name of ['SECURITY_EVENT_IP', 'SECURITY_EVENT', 'AUDIT', 'APP_SESSION', 'PROCESS_TYPE', 'MACROPROCESS', 'ADMIN_CONTROL', 'DEMO_IDENTITY', 'USER_PROFILE', 'APP_PROFILE', 'USER_IDENTITY', 'APP_USER']) {
      await queryRunner.query(`DROP TABLE ${table(name)} CASCADE CONSTRAINTS PURGE`);
    }
    await queryRunner.query(`DROP SEQUENCE "${schema}"."MACROPROCESS_CODE_SEQ"`);
  }
}
