-- Run as JALLUPACHA_OWNER after applying migrations. Do not run as SYS/SYSTEM.
-- Also applied by `npm run db:grant` and `db:reset:local` (they parse the GRANT lines below).
DEFINE app_user = JALLUPACHA_APP

GRANT CREATE SESSION TO &&app_user;

GRANT SELECT ON APP_USER TO &&app_user;
GRANT SELECT ON USER_IDENTITY TO &&app_user;
GRANT SELECT ON APP_PROFILE TO &&app_user;
GRANT SELECT, INSERT, DELETE ON USER_PROFILE TO &&app_user;
GRANT SELECT ON DEMO_IDENTITY TO &&app_user;
GRANT SELECT, UPDATE ON ADMIN_CONTROL TO &&app_user;
GRANT SELECT, INSERT, UPDATE ON MACROPROCESS TO &&app_user;
GRANT SELECT ON MACROPROCESS_CODE_SEQ TO &&app_user;
GRANT SELECT, INSERT, UPDATE ON PROCESS_TYPE TO &&app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_SESSION TO &&app_user;
GRANT SELECT, INSERT ON AUDIT TO &&app_user;
GRANT SELECT, INSERT ON SECURITY_EVENT TO &&app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON SECURITY_EVENT_IP TO &&app_user;

UNDEFINE app_user
